import * as C from '../constants';
import type { MonsterConfig } from '../types';

/**
 * All monster stat/asset definitions.
 * baseHp + hpScalePerWave * waveNumber = actual HP each wave.
 * Sprites live under public/quoctienkt/sinhtumon/monsters/...
 */
export const monstersConfig: Record<string, MonsterConfig> = {
  // ── Ground Monsters ──────────────────────────────────────────────
  [C.MONSTER_GRUNT]: {
    goldOnDead: 15,
    moveType: C.MONSTER_MOVE_TYPE_GROUND,
    armor: 0,
    spriteKey: C.MONSTER_GRUNT,
    assetPath: '/monsters/ani_beast.png',
    frameWidth: 32,
    frameHeight: 53,
    displayWidth: 32,
    displayHeight: 53,
    hitCircleRadius: 10,
    hitCircleOffsetX: 3,
    hitCircleOffsetY: 15,
    walkFrames: { right: [0, 5], left: [6, 11], down: [0, 5], up: [6, 11] },
    baseSpeed: 75,
    baseHp: 80,
    hpScalePerWave: 50,
  },

  [C.MONSTER_ORC]: {
    goldOnDead: 25,
    moveType: C.MONSTER_MOVE_TYPE_GROUND,
    armor: 0,
    spriteKey: C.MONSTER_ORC,
    assetPath: '/monsters/orc.png',
    frameWidth: 48,
    frameHeight: 64,
    displayWidth: 42,
    displayHeight: 56,
    hitCircleRadius: 14,
    hitCircleOffsetX: 4,
    hitCircleOffsetY: 8,
    walkFrames: { right: [0, 5], left: [6, 11], down: [0, 5], up: [6, 11] },
    baseSpeed: 60,
    baseHp: 200,
    hpScalePerWave: 80,
  },

  [C.MONSTER_TROLL]: {
    goldOnDead: 35,
    moveType: C.MONSTER_MOVE_TYPE_GROUND,
    armor: 0.35,
    spriteKey: C.MONSTER_TROLL,
    assetPath: '/monsters/troll.png',
    frameWidth: 48,
    frameHeight: 64,
    displayWidth: 48,
    displayHeight: 60,
    hitCircleRadius: 16,
    hitCircleOffsetX: 4,
    hitCircleOffsetY: 8,
    walkFrames: { right: [0, 5], left: [6, 11], down: [0, 5], up: [6, 11] },
    baseSpeed: 40,
    baseHp: 400,
    hpScalePerWave: 150,
  },

  [C.MONSTER_MUMMY]: {
    goldOnDead: 20,
    moveType: C.MONSTER_MOVE_TYPE_GROUND,
    armor: 0,
    regenPerSec: 8, // regenerates HP while alive
    spriteKey: C.MONSTER_MUMMY,
    assetPath: '/assets/monsters/ground/mummy/walk.png',
    frameWidth: 37,
    frameHeight: 45,
    displayWidth: 37,
    displayHeight: 45,
    hitCircleRadius: 12,
    hitCircleOffsetX: 4,
    hitCircleOffsetY: 10,
    walkFrames: { right: [0, 5], left: [6, 11], down: [0, 5], up: [6, 11] },
    baseSpeed: 55,
    baseHp: 130,
    hpScalePerWave: 60,
  },

  [C.MONSTER_SPIDER]: {
    goldOnDead: 12,
    moveType: C.MONSTER_MOVE_TYPE_GROUND,
    armor: 0,
    spriteKey: C.MONSTER_SPIDER,
    assetPath: '/monsters/spider.png',
    frameWidth: 40,
    frameHeight: 32,
    displayWidth: 36,
    displayHeight: 28,
    hitCircleRadius: 11,
    hitCircleOffsetX: 4,
    hitCircleOffsetY: 4,
    walkFrames: { right: [0, 5], left: [6, 11], down: [0, 5], up: [6, 11] },
    baseSpeed: 115,
    baseHp: 60,
    hpScalePerWave: 28,
  },

  // ── Flying Monsters ──────────────────────────────────────────────
  [C.MONSTER_HARPY]: {
    goldOnDead: 10,
    moveType: C.MONSTER_MOVE_TYPE_FLY,
    isFlying: true,
    armor: 0,
    spriteKey: C.MONSTER_HARPY,
    assetPath: '/monsters/flying/harpy/fly.png',
    frameWidth: 70,
    frameHeight: 65,
    displayWidth: 44,
    displayHeight: 44,
    hitCircleRadius: 15,
    hitCircleOffsetX: 30,
    hitCircleOffsetY: 28,
    walkFrames: { fly: [0, 19] },
    baseSpeed: 90,
    baseHp: 65,
    hpScalePerWave: 35,
  },

  [C.MONSTER_BAT]: {
    goldOnDead: 8,
    moveType: C.MONSTER_MOVE_TYPE_FLY,
    isFlying: true,
    armor: 0,
    spriteKey: C.MONSTER_BAT,
    assetPath: '/monsters/bat.png',
    frameWidth: 40,
    frameHeight: 32,
    displayWidth: 32,
    displayHeight: 26,
    hitCircleRadius: 9,
    hitCircleOffsetX: 6,
    hitCircleOffsetY: 4,
    walkFrames: { fly: [0, 5] },
    baseSpeed: 145,
    baseHp: 40,
    hpScalePerWave: 18,
  },

  [C.MONSTER_DRAGON]: {
    goldOnDead: 55,
    moveType: C.MONSTER_MOVE_TYPE_FLY,
    isFlying: true,
    armor: 0,
    spriteKey: C.MONSTER_DRAGON,
    assetPath: '/monsters/dragon.png',
    frameWidth: 64,
    frameHeight: 64,
    displayWidth: 60,
    displayHeight: 56,
    hitCircleRadius: 22,
    hitCircleOffsetX: 16,
    hitCircleOffsetY: 12,
    walkFrames: { fly: [0, 5] },
    baseSpeed: 65,
    baseHp: 450,
    hpScalePerWave: 200,
  },

  // ── Bosses ───────────────────────────────────────────────────────
  [C.BOSS_GOLEM]: {
    goldOnDead: 150,
    moveType: C.MONSTER_MOVE_TYPE_GROUND,
    isBoss: true,
    armor: 0.25,
    spriteKey: C.BOSS_GOLEM,
    assetPath: '/monsters/boss_golem.png',
    frameWidth: 64,
    frameHeight: 80,
    displayWidth: 72,
    displayHeight: 80,
    hitCircleRadius: 30,
    hitCircleOffsetX: 14,
    hitCircleOffsetY: 14,
    walkFrames: { right: [0, 5], left: [6, 11], down: [0, 5], up: [6, 11] },
    baseSpeed: 35,
    baseHp: 2500,
    hpScalePerWave: 0,
  },

  [C.BOSS_DEMON]: {
    goldOnDead: 200,
    moveType: C.MONSTER_MOVE_TYPE_FLY,
    isBoss: true,
    isFlying: true,
    armor: 0.15,
    spriteKey: C.BOSS_DEMON,
    assetPath: '/monsters/boss_demon.png',
    frameWidth: 64,
    frameHeight: 80,
    displayWidth: 72,
    displayHeight: 80,
    hitCircleRadius: 28,
    hitCircleOffsetX: 16,
    hitCircleOffsetY: 16,
    walkFrames: { fly: [0, 5] },
    baseSpeed: 50,
    baseHp: 4000,
    hpScalePerWave: 0,
  },
};
